"""
Semantic Pruner — AST 노이즈 제거 규칙

각 코드 라인을 다음 5개 카테고리로 분류한다:
  - IMPORT    : import 문
  - COMMENT   : 주석, docstring
  - CONFIG    : 환경 설정 상수 (ALL_CAPS = value)
  - GENERATED : 자동 생성 파일/섹션 마커
  - LOGIC     : 그 외 실질 로직 (빈 줄 포함)

분류 우선순위: GENERATED > IMPORT > COMMENT > CONFIG > LOGIC
  (GENERATED는 주석 내부에 위치하기 때문에 COMMENT보다 먼저 검사)
"""
import re
from enum import StrEnum

from domain.identity.models import PureContribution


class PruningCategory(StrEnum):
    IMPORT = "import"
    COMMENT = "comment"
    CONFIG = "config"
    GENERATED = "generated"
    LOGIC = "logic"


# ---------------------------------------------------------------------------
# 컴파일된 정규식 — 모듈 로딩 시 한 번만 컴파일
# ---------------------------------------------------------------------------

# GENERATED: "generated", "auto-generated", "autogenerated", "do not edit" 포함
_RE_GENERATED = re.compile(
    r"(generated|auto[-\s]?generated|autogenerated|do\s+not\s+edit)",
    re.IGNORECASE,
)

# IMPORT: 줄 시작(strip 후)이 "import " 또는 "from ... import"
_RE_IMPORT = re.compile(r"^(import\s|from\s+\S+\s+import)")

# COMMENT: #, //, /*, */, * (JSDoc), """, '''
_RE_COMMENT = re.compile(r'^(#|//|/\*|\*/|\*\s|"""|\'\'\')')

# CONFIG: ALL_CAPS_NAME = value (밑줄 허용, 반드시 대문자+숫자+밑줄 조합, 최소 2글자)
# 소문자가 포함되면 CONFIG가 아닌 LOGIC
_RE_CONFIG = re.compile(r"^[A-Z][A-Z0-9_]*\s*=")


def classify_line(line: str) -> PruningCategory:
    """
    단일 코드 라인을 PruningCategory로 분류한다.

    분류 우선순위: GENERATED > IMPORT > COMMENT > CONFIG > LOGIC
    """
    stripped = line.strip()

    # 1. GENERATED — 주석 안에 생성 마커가 있으므로 COMMENT보다 먼저 검사
    if _RE_GENERATED.search(stripped):
        return PruningCategory.GENERATED

    # 2. IMPORT
    if _RE_IMPORT.match(stripped):
        return PruningCategory.IMPORT

    # 3. COMMENT
    if _RE_COMMENT.match(stripped):
        return PruningCategory.COMMENT

    # 4. CONFIG — ALL_CAPS 상수 할당
    if _RE_CONFIG.match(stripped):
        return PruningCategory.CONFIG

    # 5. LOGIC (기본값 — 빈 줄 포함)
    return PruningCategory.LOGIC


def prune_contribution(
    file_path: str,
    language: str,
    lines: list[str],
) -> PureContribution:
    """
    파일의 각 라인을 분류하고 카테고리별 카운트를 집계하여
    PureContribution 모델로 반환한다.

    - function_bodies는 이 단계에서 빈 리스트로 초기화한다.
      (함수 본문 추출은 AST 어댑터 계층 책임)
    """
    removed_imports = 0
    removed_comments = 0
    removed_config = 0
    removed_generated = 0
    pure_logic_lines = 0

    for line in lines:
        category = classify_line(line)
        match category:
            case PruningCategory.IMPORT:
                removed_imports += 1
            case PruningCategory.COMMENT:
                removed_comments += 1
            case PruningCategory.CONFIG:
                removed_config += 1
            case PruningCategory.GENERATED:
                removed_generated += 1
            case PruningCategory.LOGIC:
                pure_logic_lines += 1

    return PureContribution(
        file_path=file_path,
        language=language,
        total_lines=len(lines),
        pure_logic_lines=pure_logic_lines,
        removed_imports=removed_imports,
        removed_comments=removed_comments,
        removed_config=removed_config,
        removed_generated=removed_generated,
        function_bodies=[],
    )
