"""
Vibector Worker (W3) — AI 코드 탐지 (WPM 분석).

LLM 기반: 코드 스니펫의 작성 패턴을 분석하여 AI 생성 코드 의심도를 판별.
전용 인프라 어댑터 없음 → InstructorClient로 구현.
"""
from __future__ import annotations

import logging
from typing import Any

from pydantic import BaseModel, Field

from application.states.forensic_state import ForensicState
from infrastructure.llm.instructor_client import InstructorClient

logger = logging.getLogger(__name__)


class VibectorResult(BaseModel):
    """Vibector 분석 결과 — 단일 코드 스니펫."""

    file_path: str
    ai_suspicion_score: float = Field(ge=0.0, le=1.0)
    reasoning: str
    indicators: list[str]


class VibectorBatchResult(BaseModel):
    """Vibector 배치 분석 결과."""

    results: list[VibectorResult]
    overall_ai_ratio: float = Field(ge=0.0, le=1.0)


VIBECTOR_SYSTEM_PROMPT = """You are an AI code authorship detector. Analyze code snippets to determine if they were likely written by a human or generated by AI.

For each code snippet, evaluate:
1. Naming patterns (AI tends to use overly descriptive or generic names)
2. Comment density and style (AI adds more uniform comments)
3. Code structure regularity (AI code is often more uniform)
4. Error handling patterns (AI adds comprehensive but generic error handling)
5. Import organization (AI organizes imports very consistently)

Return a suspicion score from 0.0 (definitely human) to 1.0 (definitely AI-generated).
Be conservative — only flag code with strong indicators."""


async def vibector_worker(state: ForensicState) -> dict[str, Any]:
    """코드 스니펫의 AI 생성 의심도를 LLM으로 분석한다."""
    cleaned_diffs = state.get("cleaned_diffs", [])

    if not cleaned_diffs:
        return {"vibector_scores": []}

    # 분석할 코드 스니펫 준비 (최대 20개)
    snippets = []
    for diff in cleaned_diffs[:20]:
        bodies = diff.get("function_bodies", [])
        if bodies:
            snippets.append({
                "file_path": diff["file_path"],
                "code": "\n\n".join(bodies[:3]),  # 파일당 최대 3개 함수
            })

    if not snippets:
        return {"vibector_scores": []}

    # LLM 분석
    import os

    client = InstructorClient(
        api_key=os.environ.get("LLM_API_KEY", ""),
        base_url=os.environ.get("LLM_BASE_URL", "https://api.moonshot.cn/v1"),
    )

    snippet_text = "\n---\n".join(
        f"File: {s['file_path']}\n```\n{s['code'][:2000]}\n```" for s in snippets
    )

    try:
        result = await client.create(
            response_model=VibectorBatchResult,
            messages=[
                {"role": "system", "content": VIBECTOR_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze these code snippets:\n\n{snippet_text}"},
            ],
            temperature=0.3,
        )
        return {"vibector_scores": [r.model_dump() for r in result.results]}
    except Exception as e:
        logger.error("vibector_worker failed: %s", e)
        return {"vibector_scores": []}
