services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: jittda_tunnel_gateway
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - public_net

networks:
  public_net:
    name: jittda-public
    driver: bridge
