"""
Semantic Pruner 도메인 테스트 — TDD

AST 노이즈 제거 규칙:
  각 코드 라인을 import / comment / config / generated / logic 으로 분류하고
  PureContribution 모델로 집계한다.
"""
import pytest

from domain.identity.semantic_pruner import PruningCategory, classify_line, prune_contribution


# ---------------------------------------------------------------------------
# classify_line — parametrize
# ---------------------------------------------------------------------------


class TestClassifyLine:
    @pytest.mark.parametrize(
        "line, expected",
        [
            # IMPORT
            ("import os", PruningCategory.IMPORT),
            ("import sys", PruningCategory.IMPORT),
            ("from pathlib import Path", PruningCategory.IMPORT),
            ("from . import utils", PruningCategory.IMPORT),
            ("from ..domain import models", PruningCategory.IMPORT),
            # COMMENT
            ("# This is a comment", PruningCategory.COMMENT),
            ("// javascript comment", PruningCategory.COMMENT),
            ("/* block comment */", PruningCategory.COMMENT),
            ("*/", PruningCategory.COMMENT),
            ("* @param foo", PruningCategory.COMMENT),
            ('"""docstring"""', PruningCategory.COMMENT),
            ("'''docstring'''", PruningCategory.COMMENT),
            # CONFIG
            ("DEBUG = True", PruningCategory.CONFIG),
            ("DATABASE_URL = 'postgres://...'", PruningCategory.CONFIG),
            ("MAX_RETRIES = 3", PruningCategory.CONFIG),
            ("LOG_LEVEL = 'INFO'", PruningCategory.CONFIG),
            # GENERATED (takes priority over COMMENT)
            ("# Generated by protobuf", PruningCategory.GENERATED),
            ("# auto-generated", PruningCategory.GENERATED),
            ("# DO NOT EDIT", PruningCategory.GENERATED),
            ("// autogenerated file", PruningCategory.GENERATED),
            ("# This file is auto-generated. Do not edit.", PruningCategory.GENERATED),
            # LOGIC
            ("def calculate(x, y):", PruningCategory.LOGIC),
            ("    return x + y", PruningCategory.LOGIC),
            ("class UserService:", PruningCategory.LOGIC),
            ("    if x > 0:", PruningCategory.LOGIC),
            ("result = compute()", PruningCategory.LOGIC),
            ("", PruningCategory.LOGIC),  # empty line → LOGIC (not noise)
            ("    ", PruningCategory.LOGIC),  # whitespace-only → LOGIC
        ],
    )
    def test_classify_line(self, line: str, expected: PruningCategory):
        assert classify_line(line) == expected


# ---------------------------------------------------------------------------
# classify_line — edge cases
# ---------------------------------------------------------------------------


class TestClassifyLineEdgeCases:
    def test_import_with_leading_whitespace_is_not_import(self):
        """들여쓰기된 import는 LOGIC (함수 내부 지역 import)."""
        # 설계 결정: 줄 시작 strip 후 패턴 적용 — 어느 쪽이든 명확히 테스트
        # 현 구현은 strip 후 패턴 매칭이므로 들여쓰기 import도 IMPORT로 분류된다.
        result = classify_line("    import os")
        assert result == PruningCategory.IMPORT

    def test_lowercase_config_is_logic(self):
        """소문자 변수 할당은 CONFIG가 아닌 LOGIC."""
        assert classify_line("result = compute()") == PruningCategory.LOGIC

    def test_partial_caps_is_logic(self):
        """일부만 대문자인 변수는 CONFIG가 아닌 LOGIC."""
        assert classify_line("MyClass = type('MyClass', (), {})") == PruningCategory.LOGIC


# ---------------------------------------------------------------------------
# prune_contribution
# ---------------------------------------------------------------------------


class TestPruneContribution:
    def test_mixed_content_counts(self):
        """혼합 콘텐츠에서 카테고리별 카운트가 정확해야 한다."""
        lines = [
            "import os",                        # IMPORT
            "from pathlib import Path",         # IMPORT
            "# comment",                        # COMMENT
            "DEBUG = True",                     # CONFIG
            "# auto-generated",                # GENERATED
            "def foo():",                       # LOGIC
            "    return 1",                     # LOGIC
        ]
        result = prune_contribution("src/foo.py", "Python", lines)

        assert result.file_path == "src/foo.py"
        assert result.language == "Python"
        assert result.total_lines == 7
        assert result.removed_imports == 2
        assert result.removed_comments == 1
        assert result.removed_config == 1
        assert result.removed_generated == 1
        assert result.pure_logic_lines == 2

    def test_mixed_content_purity_ratio(self):
        """혼합 콘텐츠의 purity_ratio가 정확해야 한다."""
        lines = [
            "import os",        # IMPORT
            "# comment",        # COMMENT
            "DEBUG = True",     # CONFIG
            "def foo():",       # LOGIC
            "    return 1",     # LOGIC
        ]
        result = prune_contribution("src/foo.py", "Python", lines)
        # 2 logic / 5 total = 0.4
        assert result.purity_ratio == pytest.approx(0.4)

    def test_all_logic_purity_ratio_is_one(self):
        """모든 라인이 LOGIC이면 purity_ratio == 1.0."""
        lines = [
            "def foo():",
            "    return 1",
            "class Bar:",
            "    pass",
        ]
        result = prune_contribution("src/foo.py", "Python", lines)
        assert result.pure_logic_lines == 4
        assert result.purity_ratio == pytest.approx(1.0)

    def test_empty_file_total_lines_zero(self):
        """빈 파일은 total_lines == 0이고 purity_ratio == 0.0."""
        result = prune_contribution("src/empty.py", "Python", [])
        assert result.total_lines == 0
        assert result.pure_logic_lines == 0
        assert result.purity_ratio == 0.0

    def test_empty_file_all_removed_counts_zero(self):
        """빈 파일은 모든 removed 필드가 0."""
        result = prune_contribution("src/empty.py", "Python", [])
        assert result.removed_imports == 0
        assert result.removed_comments == 0
        assert result.removed_config == 0
        assert result.removed_generated == 0

    def test_function_bodies_empty_list(self):
        """prune_contribution은 function_bodies를 빈 리스트로 초기화한다."""
        lines = ["import os", "DEBUG = True"]
        result = prune_contribution("src/foo.py", "Python", lines)
        assert result.function_bodies == []

    def test_all_noise_purity_ratio_is_zero(self):
        """모두 노이즈 라인이면 purity_ratio == 0.0."""
        lines = [
            "import os",
            "# comment",
            "DEBUG = True",
            "# auto-generated",
        ]
        result = prune_contribution("src/foo.py", "Python", lines)
        assert result.pure_logic_lines == 0
        assert result.purity_ratio == pytest.approx(0.0)

    def test_language_and_path_stored(self):
        """file_path와 language가 그대로 저장된다."""
        result = prune_contribution("src/utils/helper.ts", "TypeScript", ["const x = 1;"])
        assert result.file_path == "src/utils/helper.ts"
        assert result.language == "TypeScript"
